# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://www.mariapmartinez.com
baseurl: /
title: María Paz Martinez
author: María Paz Martinez
description: Personal website for Maria Paz Martinez
avatar: profile.png
email: contact@mariapmartinez.com
github: mpmarti # username
#twitter: mpzmarti
linkedin: maría-paz-martínez-vásquez-66a6453b
#stackoverflow: username   #e.g: users/2735833/proton1h1
#medium: username #e.g: NobelPeaceOslo
#Comment out if you don't want disqus
#disqus: username
#google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
